### ISSUE TITLE
Can not login from module "Login Box" after upgrade to phpBB 3.2.6

### ISSUE THREAD

**Issue by demonlibra** [blitze/phpBB-ext-sitemaker#49]
phpBB 3.2.6
PHP 7.1.11
phpBB SiteMaker 3.1.1

After try to login from module "Login Box" get error "The submitted form was invalid. Try submitting again."
From standart page "ucp.php?mode=login" logined without problem.

**Comment by RubenDebusscherOdisee** [comment]
phpBB 3.2.7
PHP 7.2.18
phpBB SiteMaker 3.1.1

It appears to be a problem to the password field, because when I try to login by the original form, and succeed, I get a notification that there was 1 failed login attempt (thanks to another phpbb add-on).  This implies the Username field was correctly sent.

**Comment by demonlibra** [comment]
This problem already fixed in SiteMaker 3.2.0

**Comment by mfilos** [comment]
Sorry but downloaded yesterday the whole branch and this issue still stands in a fresh installation of phpbb 3.2.7.

**Comment by demonlibra** [comment]
Did you dowloaded version 3.2.0?
Check version in file `.../ext/blitze/sitemaker/composer.json` 
Must be
`version": "3.2.0",`

**Comment by mfilos** [comment]
Your are right!!! My version is 3.1.1 and I just realized I downloaded the "develop" branch!
Thanks a lot and sorry for wasting your time :S
